### PR TITLE
Added Bin gui

### LINKED ISSUE #72: Add custom bin view
There should be a custom bin auction view/overlay that only requires clicking the mouse twice instead of moving it to start and confirm the purchase.  
it should always display the item lore when opening and have a cancle button where it normally is (on the right)
The item lore is available as property on every flip message so should not have to be waited for to be loaded from hypixel. 
The interface should open as soon as the viewauction command is executed via a click on the message or the hotkey.
The flip message for the flip received from the server should optionally be displayed on the left side (changeable via in game setting)
The item icon should be rendered as soon as its available.

The bounty for implementing this is **200€ or 77,500 cofl coins (about 300€)**
Please keep in mind that there might be more minor adjustments until accepted.

Opening should look similar to this:

Image

### PR DESCRIPTION
**Pull request by ForBai**
I am sorry that it took so long i had school but now i am done the method to open the GUI is in the BinGuiManager.
If there are any things that you want added or removed just say it and i will try changing it.

Resolved #72

### CODE REVIEW

**Comment by ForBai** [comment]
Btw i now feel somewhat Bad so if i get the bounty i want that 20% of it go to @peletic

**Comment by Peletic** [comment]
you got it in a day ago and akwav didnt even notice smh

**Comment by Ekwav** [comment]
Hello @ForBai 
Thanks for your work so far, I couldn't get the UI to open. I hooked it up to flips but the minecraft log just prints the following:
```
[21:21:04] [Client thread/INFO]: [de.torui.coflsky.bingui.gui.BinGui:onDrawGuiScreen:61]: java.lang.NoSuchFieldException: lowerChestInventory
[21:21:04] [Client thread/INFO]: [de.torui.coflsky.bingui.gui.BinGui:onDrawGuiScreen:61]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[21:21:04] [Client thread/INFO]: [de.torui.coflsky.bingui.gui.BinGui:onDrawGuiScreen:61]: 	at de.torui.coflsky.bingui.gui.BinGui.onDrawGuiScreen(BinGui.java:57)
```
Am I right to assume that you just do this to determine if it is a BIN auction?

**Comment by ForBai** [comment]
> Hello @ForBai 
> Thanks for your work so far, I couldn't get the UI to open. I hooked it up to flips but the minecraft log just prints the following:
> ```
> [21:21:04] [Client thread/INFO]: [de.torui.coflsky.bingui.gui.BinGui:onDrawGuiScreen:61]: java.lang.NoSuchFieldException: lowerChestInventory
> [21:21:04] [Client thread/INFO]: [de.torui.coflsky.bingui.gui.BinGui:onDrawGuiScreen:61]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
> [21:21:04] [Client thread/INFO]: [de.torui.coflsky.bingui.gui.BinGui:onDrawGuiScreen:61]: 	at de.torui.coflsky.bingui.gui.BinGui.onDrawGuiScreen(BinGui.java:57)
> ```
> Am I right to assume that you just do this to determine if it is a BIN auction? 

Yes i do

**Comment by Ekwav** [comment]
image
The confirm is not centered

**Comment by ForBai** [comment]
fix will take some time because minecraft being minecraft

**Comment by Ekwav** [comment]
There are a few more issues 
* The background still goes all gray from time to time 
image
* Clicking when the GUI opens presses the cancel button barrier block. It should not cancel when not moving the mouse.

* The flip message isn't rendered correctly 
image

**Comment by ForBai** [comment]
will be fixed soon eta. 1-3h

**Comment by Ekwav** [comment]
Thanks for your updates. There are a few more open issues.
image
* the main point of only having to click twice doesn't work as the click goes to the barrier
* the description and message should be rendered immediately after the ui open was called

image
* The incorrect rendering in my last review referred to the symbol on the left
* Please move the information out of the corners and next to the Bin Auction View 
* Also move the close next to/onto the view 

I changed a few things around in the hook up glue, clicking a flip in chat now triggers your code correctly and I allowed myself to remove the confirm from overlapping the inventory

**Comment by Ekwav** [comment]
BIN ui target
Getting closer to the target although still two mayor issues:
* The current version doesn't satisfy the requirement that there is no mouse movement required anymore. I suggest rendering the buttons like in the mock above
* The isn't rendered immediately (only when hypixel responded) To inform users that the gui is opening the overlay should be rendered immediately and only stop doing so if A) the cancel button or escape is pressed B) Hypixel responds with a message that indicates the Auction doesn't exist (again I can handle that if you expose a method)

**Comment by matthias-luger** [comment]
close as it is implemented into #78

**Pull request closed without merging**
